### ISSUE TITLE
Namespaced keys in StorageModule

### ISSUE THREAD

**Issue by perarnborg** [Aventyret/lionel-oauth-client#72]
I think all keys should be namespaced by the library in the storage (localStorage / sessionStorage). The key `state` for example is a bit to generic and might collide with an applications storage pattern.

**Comment by perarnborg** [comment]
Question: Maybe keys should also be prefixed with a hash of issuer + client_id? For example to avoid two applications running on localhost:3000 against different issuers to accidentaly retrieve eachothers tokens...

**Comment by dennerkrans** [comment]
> Question: Maybe keys should also be prefixed with a hash of issuer + client_id? For example to avoid two applications running on localhost:3000 against different issuers to accidentaly retrieve eachothers tokens...

I think this sounds like a good idea.
